// <auto-generated />
using System;
using DESOFT.Server.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DESOFT.Server.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DESOFT.Server.API.Domain.Entities.ComicBooks.ComicBook", b =>
                {
                    b.Property<int>("ComicBookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("ID of the Comic Book.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComicBookId"));

                    b.Property<DateTime>("AlteracaoData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 30, 21, 34, 25, 36, DateTimeKind.Utc).AddTicks(226))
                        .HasComment("Data de alteração do registo (auditoria).");

                    b.Property<int>("AlteracaoUtilizadorId")
                        .HasColumnType("int")
                        .HasComment("Identificador do utilizador que alterou o registo (auditoria).");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Author");

                    b.Property<DateTime>("CriacaoData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 30, 21, 34, 25, 35, DateTimeKind.Utc).AddTicks(9817))
                        .HasComment("Data de criação do registo (auditoria).");

                    b.Property<int>("CriacaoUtilizadorId")
                        .HasColumnType("int")
                        .HasComment("Identificador do utilizador que criou o registo (auditoria).");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Description");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price");

                    b.Property<DateOnly>("PublishingDate")
                        .HasColumnType("date")
                        .HasComment("Publishing Date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Title");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Version");

                    b.HasKey("ComicBookId");

                    b.HasIndex("OrderId");

                    b.ToTable("ComicBook", (string)null);
                });

            modelBuilder.Entity("DESOFT.Server.API.Domain.Entities.Inventory.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("ID of the Inventory");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<DateTime>("AlteracaoData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 30, 21, 34, 25, 36, DateTimeKind.Utc).AddTicks(5355))
                        .HasComment("Data de alteração do registo (auditoria).");

                    b.Property<int>("AlteracaoUtilizadorId")
                        .HasColumnType("int")
                        .HasComment("Identificador do utilizador que alterou o registo (auditoria).");

                    b.Property<int>("ComicBookId")
                        .HasColumnType("int")
                        .HasComment("ID of the ComicBook");

                    b.Property<DateTime>("CriacaoData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 30, 21, 34, 25, 36, DateTimeKind.Utc).AddTicks(4934))
                        .HasComment("Data de criação do registo (auditoria).");

                    b.Property<int>("CriacaoUtilizadorId")
                        .HasColumnType("int")
                        .HasComment("Identificador do utilizador que criou o registo (auditoria).");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Quantity");

                    b.HasKey("InventoryId");

                    b.HasIndex("ComicBookId");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("DESOFT.Server.API.Domain.Entities.Order.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("ID of the Order");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Address");

                    b.Property<DateTime>("AlteracaoData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 30, 21, 34, 25, 36, DateTimeKind.Utc).AddTicks(8205))
                        .HasComment("Data de alteração do registo (auditoria).");

                    b.Property<int>("AlteracaoUtilizadorId")
                        .HasColumnType("int")
                        .HasComment("Identificador do utilizador que alterou o registo (auditoria).");

                    b.Property<DateTime>("CriacaoData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 30, 21, 34, 25, 36, DateTimeKind.Utc).AddTicks(7882))
                        .HasComment("Data de criação do registo (auditoria).");

                    b.Property<int>("CriacaoUtilizadorId")
                        .HasColumnType("int")
                        .HasComment("Identificador do utilizador que criou o registo (auditoria).");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Total Cost");

                    b.HasKey("OrderId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("DESOFT.Server.API.Domain.Entities.Order.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("ID of the OrderItem");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<DateTime>("AlteracaoData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 30, 21, 34, 25, 37, DateTimeKind.Utc).AddTicks(4400))
                        .HasComment("Data de alteração do registo (auditoria).");

                    b.Property<int>("AlteracaoUtilizadorId")
                        .HasColumnType("int")
                        .HasComment("Identificador do utilizador que alterou o registo (auditoria).");

                    b.Property<int>("ComicBookId")
                        .HasColumnType("int")
                        .HasComment("ID of the ComicBook");

                    b.Property<DateTime>("CriacaoData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 30, 21, 34, 25, 37, DateTimeKind.Utc).AddTicks(3750))
                        .HasComment("Data de criação do registo (auditoria).");

                    b.Property<int>("CriacaoUtilizadorId")
                        .HasColumnType("int")
                        .HasComment("Identificador do utilizador que criou o registo (auditoria).");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasComment("ID of the Order");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Quantity");

                    b.HasKey("OrderItemId");

                    b.HasIndex("ComicBookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("DESOFT.Server.API.Domain.Entities.ShoppingCart.ShoppingCart", b =>
                {
                    b.Property<int>("ShoppingCartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("ID of the ShoppingCart");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingCartId"));

                    b.Property<DateTime>("AlteracaoData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 30, 21, 34, 25, 38, DateTimeKind.Utc).AddTicks(3143))
                        .HasComment("Data de alteração do registo (auditoria).");

                    b.Property<int>("AlteracaoUtilizadorId")
                        .HasColumnType("int")
                        .HasComment("Identificador do utilizador que alterou o registo (auditoria).");

                    b.Property<DateTime>("CriacaoData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 30, 21, 34, 25, 38, DateTimeKind.Utc).AddTicks(2816))
                        .HasComment("Data de criação do registo (auditoria).");

                    b.Property<int>("CriacaoUtilizadorId")
                        .HasColumnType("int")
                        .HasComment("Identificador do utilizador que criou o registo (auditoria).");

                    b.HasKey("ShoppingCartId");

                    b.ToTable("ShoppingCart", (string)null);
                });

            modelBuilder.Entity("DESOFT.Server.API.Domain.Entities.ShoppingCart.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("ID of the ShoppingCartItem");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingCartItemId"));

                    b.Property<DateTime>("AlteracaoData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 30, 21, 34, 25, 38, DateTimeKind.Utc).AddTicks(6494))
                        .HasComment("Data de alteração do registo (auditoria).");

                    b.Property<int>("AlteracaoUtilizadorId")
                        .HasColumnType("int")
                        .HasComment("Identificador do utilizador que alterou o registo (auditoria).");

                    b.Property<int>("ComicBookId")
                        .HasColumnType("int")
                        .HasComment("ID of the Comic Book");

                    b.Property<DateTime>("CriacaoData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 4, 30, 21, 34, 25, 38, DateTimeKind.Utc).AddTicks(6048))
                        .HasComment("Data de criação do registo (auditoria).");

                    b.Property<int>("CriacaoUtilizadorId")
                        .HasColumnType("int")
                        .HasComment("Identificador do utilizador que criou o registo (auditoria).");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("ComicBookId");

                    b.ToTable("ShoppingCartItem", (string)null);
                });

            modelBuilder.Entity("DESOFT.Server.API.Domain.Entities.ComicBooks.ComicBook", b =>
                {
                    b.HasOne("DESOFT.Server.API.Domain.Entities.Order.Order", null)
                        .WithMany("ComicBook")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("DESOFT.Server.API.Domain.Entities.Inventory.Inventory", b =>
                {
                    b.HasOne("DESOFT.Server.API.Domain.Entities.ComicBooks.ComicBook", "ComicBook")
                        .WithMany("Inventory")
                        .HasForeignKey("ComicBookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ComicBook");
                });

            modelBuilder.Entity("DESOFT.Server.API.Domain.Entities.Order.OrderItem", b =>
                {
                    b.HasOne("DESOFT.Server.API.Domain.Entities.ComicBooks.ComicBook", "ComicBook")
                        .WithMany("OrderItems")
                        .HasForeignKey("ComicBookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DESOFT.Server.API.Domain.Entities.Order.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ComicBook");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DESOFT.Server.API.Domain.Entities.ShoppingCart.ShoppingCartItem", b =>
                {
                    b.HasOne("DESOFT.Server.API.Domain.Entities.ComicBooks.ComicBook", "ComicBook")
                        .WithMany("ShoppingCartItem")
                        .HasForeignKey("ComicBookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ComicBook");
                });

            modelBuilder.Entity("DESOFT.Server.API.Domain.Entities.ComicBooks.ComicBook", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("OrderItems");

                    b.Navigation("ShoppingCartItem");
                });

            modelBuilder.Entity("DESOFT.Server.API.Domain.Entities.Order.Order", b =>
                {
                    b.Navigation("ComicBook");

                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
