name: Automatic Pipeline Workflow
on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release